# Generated by Django 6.0.6 on 2026-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
