# Generated by Django 6.0.8 on 2026-08-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reminderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICandidateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField(default=0.0)),
                ('ai_interview_score', models.FloatField(default=0.0)),
                ('composite_score', models.FloatField(default=0.0)),
                ('recommendation', models.CharField(choices=[('strong_hire', 'Strong Hire'), ('hire', 'Hire'), ('neutral', 'Needs Second Review'), ('do_not_hire', 'Do Not Hire')], default='hire', max_length=30)),
                ('executive_summary', models.TextField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('structured_report', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_candidate_report', to='core.application')),
            ],
            options={
                'db_table': 'ai_candidate_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
