# Generated by Django 6.0.6 on 2026-07-23 12:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candidate_education_candidate_expected_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=core.models.candidate_resume_path),
        ),
    ]
