# Generated by Django 6.0.8 on 2026-08-31 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_aicandidatereport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityFailureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("unauthorized_access", "Unauthorized Access Attempt"),
                            ("forbidden_role", "Role Permission Violation"),
                            ("system_exception", "System Runtime Exception"),
                            ("service_retry", "Service Retry Failure"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Security Warning"),
                            ("critical", "Critical Security Failure"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("http_method", models.CharField(max_length=10)),
                ("user_identifier", models.CharField(blank=True, max_length=150, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("exception_details", models.TextField(blank=True, null=True)),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_security_failure_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemAuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User Action"),
                            ("admin", "Admin Action"),
                            ("ai_system", "AI System Action"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "action_category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication & Access"),
                            ("job", "Job Management"),
                            ("application", "Application Status Change"),
                            ("ai_eval", "AI Screening & Scoring"),
                            ("scheduling", "Interview Scheduling"),
                            ("admin_mod", "Admin Moderation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_name", models.CharField(max_length=150)),
                ("target_entity", models.CharField(blank=True, max_length=100, null=True)),
                ("target_id", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("payload_snapshot", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_trails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_audit_trails",
                "ordering": ["-timestamp"],
            },
        ),
    ]
