# Generated by Django 6.0.8 on 2026-09-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_usersubscription_grace_period_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["job", "status"], name="idx_app_job_status"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["candidate", "created_at"], name="idx_app_cand_created"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["employer", "status"], name="idx_job_employer_status"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["job_type", "created_at"], name="idx_job_type_created"),
        ),
    ]
