# Generated by Django 6.0.8 on 2026-08-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationauditlog',
            name='ats_score',
            field=models.FloatField(default=0.0, help_text='Calculated ATS suitability score percentage (0-100)'),
        ),
    ]
