# Generated by Django 6.0.8 on 2026-08-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_applicationauditlog_ats_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationauditlog',
            name='ats_score',
        ),
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(default=0.0, help_text='Calculated ATS suitability score percentage (0-100)'),
        ),
    ]
