# Generated by Django 6.0.8 on 2026-08-18 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aicall'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_data', models.JSONField(blank=True, help_text='Structured JSON of the full transcript', null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_session', to='core.aicall')),
            ],
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('asked_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.aiinterviewsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('audio_url', models.URLField(blank=True, help_text='URL to the voice-to-text audio if available', null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='core.aiquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="e.g., 'Initiated', 'Failed', 'Completed'", max_length=255)),
                ('reason', models.TextField(blank=True, help_text='Why this action was performed or why it failed', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ai_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.aicall')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who initiated the call (if manual), else None for automated', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
