server {
    listen 80;
    server_name api.zecpath.com 127.0.0.1;

    client_max_body_size 25M;

    location /static/ {
        alias /home/ubuntu/zecpath-backend/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/zecpath-backend/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/zecpath-backend/zecpath.sock;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
