"""
Django settings for zecpath_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--06r2=&q3z!r5xp!lcr&1wi@289n3xb647b3*5fn9z19b94)!l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'rest_framework_simplejwt.token_blacklist',
    'core',
    
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # 10 jobs per page
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zecpath_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zecpath_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AUTH_USER_MODEL = "core.User"



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',

    # Day 14: Pagination & Filtering Configuration
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Default 10 items per page
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),

    # Day 43: API Throttling & Rate Limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',           # Anonymous users rate limit
        'user': '120/minute',          # Authenticated users rate limit
        'ai_abuse': '5/minute',        # Strict throttle for expensive AI endpoints
        'auth_strict': '5/minute',     # Strict throttle for login / sensitive attempts
    },
}

# Email Backend Configuration (Console Output for local testing)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Zecpath Automated Assistant <no-reply@zecpath.com>'

# Celery Configuration (Redis Broker & Result Backend)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Eager execution fallback for dev environments where Redis broker is offline
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'True').lower() in ('true', '1')
CELERY_TASK_EAGER_PROPAGATES = True


# Celery Beat Periodic Tasks Schedule (Cron Jobs)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'periodic-auto-screening-hourly': {
        'task': 'core.tasks.periodic_batch_auto_screening_task',
        'schedule': crontab(minute=0),  # Runs every hour at minute 0
    },
    'periodic-analytics-digest-daily': {
        'task': 'core.tasks.periodic_system_analytics_digest_task',
        'schedule': crontab(hour=0, minute=0),  # Runs daily at midnight
    },
}


# ==============================================================================
# DAY 35: VOICE & AI INTEGRATION SETTINGS
# ==============================================================================
import os
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
VOICE_SERVICE_PROVIDER = os.getenv('VOICE_SERVICE_PROVIDER', 'mock')  # 'mock', 'twilio', 'deepgram'
DEFAULT_VOICE_LANGUAGE = 'en-US'
DEFAULT_VOICE_GENDER = 'female'  # 'male', 'female', 'neutral'
VOICE_SYNTHESIS_MODEL = 'gemini-2.5-flash'  # Or TTS voice profile
AI_SERVICE_MAX_RETRIES = 3
AI_SERVICE_TIMEOUT_SECONDS = 15

# ==============================================================================
# DAY 35: VOICE & AI INTEGRATION SETTINGS
# ==============================================================================
import os
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
VOICE_SERVICE_PROVIDER = os.getenv('VOICE_SERVICE_PROVIDER', 'mock')  # 'mock', 'twilio', 'deepgram'
DEFAULT_VOICE_LANGUAGE = 'en-US'
DEFAULT_VOICE_GENDER = 'female'  # 'male', 'female', 'neutral'
VOICE_SYNTHESIS_MODEL = 'gemini-2.5-flash'  # Or TTS voice profile
AI_SERVICE_MAX_RETRIES = 3
AI_SERVICE_TIMEOUT_SECONDS = 15

# ==============================================================================
# DAY 43: FIELD ENCRYPTION KEY FOR SENSITIVE DATA
# ==============================================================================
# Derives a 32-byte key from SECRET_KEY for Fernet symmetric encryption
FIELD_ENCRYPTION_KEY = SECRET_KEY.encode()[:32]
